"""
Loads the cleaned data into SQLite and runs every query in sql/queries.sql.
Results are written to sql/query_results.md

    python sql/run_queries.py
"""
from pathlib import Path
import re
import sqlite3
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
df = pd.read_csv(ROOT / "data" / "processed" / "sales_clean.csv.gz")
df["order_date"] = pd.to_datetime(df["order_date"]).dt.strftime("%Y-%m-%d")
for col in ("is_b2b", "is_net_sale", "has_promotion"):
    df[col] = df[col].astype(int)

con = sqlite3.connect(":memory:")
df.to_sql("sales", con, index=False)

sql_text = (ROOT / "sql" / "queries.sql").read_text(encoding="utf-8")
blocks = re.split(r"\n(?=-- Q\d+\.)", sql_text)
out = ["# SQL query results\n", "Generated by `python sql/run_queries.py` (SQLite).\n"]
for block in blocks:
    m = re.match(r"-- (Q\d+\. .+)", block)
    if not m:
        continue
    title = m.group(1)
    query = block.strip()
    result = pd.read_sql_query(query, con)
    for col in result.select_dtypes("float"):
        if (result[col].dropna() % 1 == 0).all():
            result[col] = result[col].astype("Int64")
    table = result.to_markdown(index=False, floatfmt=",.2f", intfmt=",")
    out.append(f"\n## {title}\n\n```sql\n{query}\n```\n\n{table}\n")
    print(f"{title}  ->  {len(result)} rows")

(ROOT / "sql" / "query_results.md").write_text("\n".join(out), encoding="utf-8")
print("written: sql/query_results.md")
